VER=0.5.4.2

# Must be LOWERCASE
USER=8ch9azbsfifz
REPO=librtlsdr
TAG=docker.pkg.github.com/${USER}/${REPO}/rtl_hpsdr

build:
	docker build . -t ${TAG}:${VER} -t ${TAG}:latest

run:
	docker run --rm -it -p 8080:8080 ${TAG}:${VER}

push:
	docker push ${TAG}:${VER}

